feat(tap): Page Tap Support
microsoft/playwright-sharp pull request #1014
Opened 2020-11-20 16:45 UTC by avodovnik

This PR adds support for [tap](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=pagetapselector-options).

2020-11-24 20:18 UTC, kblok commented
Can you pull from master? there were some changes in the Connection class.

2020-11-24 22:10 UTC, kblok requested changes

2020-11-26 10:25 UTC, avodovnik commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            await Page.TapAsync("div");
Is it?

https://github.com/microsoft/playwright/blob/master/test/tap.spec.ts#L50-L64

2020-11-26 10:26 UTC, avodovnik commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            await Page.TapAsync("div");
See above comment. I can't seem to find a `body` reference in the original test.

2020-11-26 10:33 UTC, avodovnik commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            Assert.Equal(0, touchStartResult.rotationAngle);
Yeah, good catch - though the value is `null` for us :)

2020-11-26 10:49 UTC, avodovnik commented on src/PlaywrightSharp/Page.cs
> +            => MainFrame.TapAsync(selector, force, noWaitAfter, modifiers, position, timeout);
Can you explain? Not sure I follow.

2020-11-26 11:20 UTC, kblok commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            Context = await Browser.NewContextAsync();
Where are we using this @avodovnik?

2020-11-26 11:20 UTC, kblok commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            await Page.TapAsync("div");
ah ok. We can leave this as is.
Consider looking at the version tag we are implementing. I was looking at the spec file on the tag v1.6.2 https://github.com/microsoft/playwright/blob/v1.6.2/test/tap.spec.ts#L50

2020-11-26 12:47 UTC, avodovnik commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            await Page.TapAsync("div");
Interesting. 

Yeah, I'd almost prefer we keep it as close to _current_ as we can, but maybe that's a conversation we should have.

2020-11-26 17:06 UTC, avodovnik commented on src/PlaywrightSharp.Tests/TapTests.cs
> +            var altKeyTask = Page.EvaluateAsync<JsonElement>(@"() =>
Great catch!

2020-11-26 17:15 UTC, kblok approved these changes

2020-11-26 17:33 UTC, merged